<a href="https://colab.research.google.com/github/Shravanikuldharan/ml-linear-regression-workshop/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Importing the dataset**

In [ ]:
data = pd.read_csv("Data.csv")
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
x = data.iloc[:,1:2].values
print(x)

[[44.]
 [27.]
 [30.]
 [38.]
 [40.]
 [35.]
 [nan]
 [48.]
 [50.]
 [37.]]


In [ ]:
from sklearn.impute import SimpleImputer
im = SimpleImputer(missing_values=np.nan, strategy='median')

In [ ]:
im.fit(x)

SimpleImputer(strategy='median')

In [ ]:
x = im.transform(x)
print(x)

[[44.]
 [27.]
 [30.]
 [38.]
 [40.]
 [35.]
 [38.]
 [48.]
 [50.]
 [37.]]


In [ ]:
y = data.iloc[:,2:3].values
print(y)

[[72000.]
 [48000.]
 [54000.]
 [61000.]
 [   nan]
 [58000.]
 [52000.]
 [79000.]
 [83000.]
 [67000.]]


In [ ]:
from sklearn.impute import SimpleImputer
im1 = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
im1.fit(y)

SimpleImputer()

In [ ]:
y = im1.transform(y)
print(y)

[[72000.        ]
 [48000.        ]
 [54000.        ]
 [61000.        ]
 [63777.77777778]
 [58000.        ]
 [52000.        ]
 [79000.        ]
 [83000.        ]
 [67000.        ]]
